#!/bin/bash

pki_dir="/etc/icinga2/pki"
fqdn=`hostname -f`
icinga2_master="xxxxxxx"
icinga2_master_port=5665
ticket="xxxxxxxx"


#Add repo
wget -O - https://debmon.org/debmon/repo.key 2>/dev/null | apt-key add - 
echo 'deb http://debmon.org/debmon debmon-jessie main' >/etc/apt/sources.list.d/debmon.list
echo 'deb http://httpredir.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/debmon.list
apt-get update  

# Client Installation
apt-get install icinga2 -y 
apt-get install nagios-plugins -y
systemctl restart  icinga2.service


####Icinga2 Configuration
mkdir $pki_dir
chown icinga:icinga $pki_dir; chmod 0700 $pki_dir;


####SSL Configuration
icinga2 pki new-cert --cn $fqdn --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt
icinga2 pki save-cert --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --host $icinga2_master
icinga2 pki request --host $icinga2_master --port $icinga2_master_port --ticket $ticket --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --ca $pki_dir/ca.key
icinga2 node setup --ticket $ticket --endpoint $icinga2_master --zone $fqdn --master_host $icinga2_master --trustedcert $pki_dir/trusted-master.crt


icinga2 feature enable command


####Configure zones
cat >/etc/icinga2/zones.conf << EOFZONECONF
/*
* Generated by Icinga 2 node setup commands
*/


object Endpoint "$icinga2_master" {
host = "$icinga2_master"
port = "5665"
}


object Zone "master" {
endpoints = [ "$icinga2_master" ]
}


object Endpoint NodeName {
}


object Zone ZoneName {
endpoints = [ NodeName ]
parent = "master"
}
EOFZONECONF

sed -i -e "s#NodeNme#\"$(hostname)\"#g;s#ZoneName#\"$(hostname)\"#g" /etc/icinga2/zones.conf

#( bellow is custom -> you do not need to remove apt I dit it because is a custom project with specific needs)

#Remove apt services-icinga2  
cd /etc/icinga2/conf.d
rm apt.conf

#http port is 80 default I need it on 8080
sed -i '/vars.http_vhosts/ a \    http_port = "8080"' hosts.conf
awk 'NR!~/^(36)$/' hosts.conf  > hosts2.conf
rm hosts.conf
mv hosts2.conf hosts.conf


#done customization


service icinga2 restart
